# fly.toml app configuration file generated for drinks-app-bitter-voice-6309 on 2024-02-15T11:43:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drinks-app-bitter-voice-6309'
primary_region = 'ord'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python3 manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
